### ISSUE TITLE
ODHack: Update Scarb/Starknet Foundry

### ISSUE THREAD

**Issue by Darlington02** [horuslabsio/Starknet-Scaffold#153]
your task is to update the `contracts` section to use:

- Scarb v2.8.3
- Starknet Foundry v0.31.0
you'd need to also update the the github workflows.

**Comment by Iwueseiter** [comment]
Ho

**Comment by Jemiiah** [comment]
I

**Comment by ShantelPeters** [comment]
Please can I be assigned to this issue @Darlington02
