### ISSUE TITLE
Smart contract verification on Voyager

### ISSUE THREAD

**Issue by Darlington02** [horuslabsio/Starknet-Scaffold#80]
The aim of Starknet Scaffold is to simplify the lives of developers. Let's simplify the way developers verify their contract within the `contracts` folder on Voyager down to running a simple npm script within the `package.json` file.

resource:
https://github.com/NethermindEth/starknet-contract-verifier

PS: issue is pending as verifier doesn't support scarb 2.6.3

**Comment by Oshioke-Salaki** [comment]
can i have this?

**Comment by Joy-Adah** [comment]
Hi @Darlington02 I'll love to work on this

**Comment by vibenedict** [comment]
i will like to jump on this issue

**Comment by MarvyNwaokobia** [comment]
Can I have this please?

**Comment by Dprof-in-tech** [comment]
good day please i would love to work on this

**Comment by VictoriaAde** [comment]
I have a good idea how to go about this.
Can I have it? 
I would love to work on it.

**Comment by od-hunter** [comment]
@Darlington02 can I work I this please? I promise to deliver
