### ISSUE TITLE
Detailed article on how to use starknet scaffold

### ISSUE THREAD

**Issue by Darlington02** [horuslabsio/Starknet-Scaffold#81]
- Will be a 2-part detailed series
- Will cover both the contract development and frontend development aspect using Starknet Scaffold
- First part on contract development, second part on frontend development
- Should clearly detail how development was made simpler thanks to Starknet Scaffold

PS: A proven track record of writing good articles is needed for this task, so please add a link to previously written articles when asking to be assigned

**Comment by od-hunter** [comment]
i

**Comment by Dprof-in-tech** [comment]
good day please i would love to work on this

**Comment by stevencartavia** [comment]
Hi, can I get this?

**Comment by Joy-Adah** [comment]
Hi @Darlington02 I'll love to work on this

**Comment by MarvyNwaokobia** [comment]
Can I have this please?

**Comment by Darlington02** [comment]
add a link to previously written article please. can't assign just anybody

**Comment by stevencartavia** [comment]
can I get one of the next issues pls?

**Comment by Immanuelolivia1** [comment]
Here is a link to my articles on  [Yakihonne ](https://yakihonne.com/users/nprofile1qyw8wumn8ghj7mn0wd68ytfsxyh8jcttd95x7mnwv5hxxmmdqyw8wumn8ghj7mn0wd68ytfsxgh8jcttd95x7mnwv5hxxmmdqy08wumn8ghj7mn0wd68ytfsxvhxgmmjv9nxzcm5dae8jtn0wfnsz9rhwden5te0wfjkccte9ejxzmt4wvhxjmcpremhxue69uhkummnw3ez6vpj9ejx7unpveskxar0wfujummjvuqzpa49eqh65e820uypyv3uuazm63ady3g4edlly4ugvcccsua2du4qej3w2f) 
i would like to work on this @Darlington02

**Comment by Calebux** [comment]
https://yakihonne.com/article/naddr1qq2457n9vdzhz5jtve2455z32en97uzlf3yhyq3qcst96d8s7sstz8wqjtnu34rkqh4wpn6yt9d48v472ja7qvl0ckasxpqqqp65w0w0hv4
Here is a link

**Comment by VictoriaAde** [comment]
Hi, I'm a technical writer.
I would like to work on this

**Comment by mimiprosper** [comment]
I would like to work on this. Am good in technical writing. Below is the link to some articles I have written:

https://medium.com/@emma.onyedika.okeke

**Comment by mimiprosper** [comment]
I would love to work on this. Am good in technical writing. Find my link below:

https://medium.com/@emma.onyedika.okeke

**Comment by petersdt** [comment]
hi @Darlington02 can interested in writing a detailed article on how to use starknet scaffold

**Comment by Gift-Naomi** [comment]
@Darlington02 If this issue is still open for contribution, i will like to work on it
Here are some merged documentations and article i have worked on https://github.com/paltalabs/create-soroban-dapp/pull/27/commits/61919f9d949cd39d324501f7283c8f8d7344cb64, https://github.com/horuslabsio/Starknet-Scaffold/blob/main/docs/src/chapter_7.md
https://hackmd.io/@xZ4BOZ5TTTy1I0ZQHXFOkg/BJi6vmIIA
